####################################################################################################
## 공용
####################################################################################################
spring:
  profiles:
    active: test
  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false
jangtari:
  name: jangtari
---
####################################################################################################
## prod
####################################################################################################
#spring.jpa.database=mysql
#spring.jpa.database-platform=org.hibernate.dialect.MySQL5InnoDBDialect
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

---
####################################################################################################
## dev
####################################################################################################
spring:
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~test:h2;MODE=MYSQL;INIT=CREATE SCHEMA IF NOT EXISTS jangtari\;SET SCHEMA jangtari;
    username: sa
    password:

---
####################################################################################################
## test
####################################################################################################
spring:
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=MYSQL;INIT=CREATE SCHEMA IF NOT EXISTS jangtari\;SET SCHEMA jangtari;
    username: sa
    password:
  h2:
    console:
      path: /h2
      enabled: true