####################################################################################################
## 공용
####################################################################################################
spring:
  profiles:
    active: dev
  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false
jangtari:
  name: jangtari
  oauth:
    callback: 'http://www.gamsk.kro.kr/Callback'
  drive:
    list: 1NzhQFXNOqY3dNYIHq0Rpf6AKZH-xHWVR, 14CKUxuVzBqPz8RDwvLvUxaOJLI1Z62XK, 1G7FMqlteOguD-St7TOIO_P6czMDD46lS
---
####################################################################################################
## prod
####################################################################################################
#spring.jpa.database=mysql
#spring.jpa.database-platform=org.hibernate.dialect.MySQL5InnoDBDialect
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

---
####################################################################################################
## dev
####################################################################################################
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test:h2;MODE=MYSQL;INIT=CREATE SCHEMA IF NOT EXISTS jangtari\;SET SCHEMA jangtari;
    username: sa
    password:

---
####################################################################################################
## test
####################################################################################################
spring:
  config:
    activate:
      on-profile: test
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=MYSQL;INIT=CREATE SCHEMA IF NOT EXISTS jangtari\;SET SCHEMA jangtari;
    username: sa
    password:
  h2:
    console:
      path: /h2
      enabled: true